// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtsbbafhdjrxygtinnmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0c2JiYWZoZGpyeHlndGlubm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjQ0ODUsImV4cCI6MjA2MjEwMDQ4NX0.0y6whaXbudIsQ7_iBlRC8XzBuS2WIFlxxDtIXeuWYPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);